### PR TITLE
build min file css latest version

### PR DESCRIPTION
**Pull request by lh0x00**

### CODE REVIEW

**Comment by lh0x00** [comment]
@marcintabaka @crookedneighbor please check it 👍

**Comment by crookedneighbor** [comment]
Did you intend to tag me?

**Comment by lh0x00** [comment]
@crookedneighbor yes, I think you should check it!

**Comment by crookedneighbor** [comment]
Woah, I completely forgot I opened a PR for this repo 3+ years ago. I'm not a maintainer of the project though, why do you need me to review it?

**Comment by lh0x00** [comment]
@crookedneighbor you don't merge it? :<

**Comment by crookedneighbor** [comment]
I'm not a member of the codrops org, so no, I don't have that permission.

**Comment by lh0x00** [comment]
@crookedneighbor oh yeah, i'm so sorry!

**Pull request closed without merging**
